CREATE TABLE CIS310Customer (
	CustID INT NOT NULL UNIQUE,
	FirstName VARCHAR(12) NOT NULL,
	LastName VARCHAR(14) NOT NULL,
	CONSTRAINT CustID_PK PRIMARY KEY (CustID)
);

CREATE TABLE CIS310Vehicle (
	VIN VARCHAR(10) UNIQUE, 
	Make VARCHAR(15),
	Model VARCHAR(20),
	CarYear DATE DEFAULT GETDATE(),
	CustID INT REFERENCES CIS310Customer(CustID),
	CONSTRAINT VIN_PK PRIMARY KEY (VIN),
	CONSTRAINT CustID_FK1 FOREIGN KEY (CustID) REFERENCES CIS310Customer(CustID)
);

CREATE TABLE CIS310Repair (
	RepairID INT UNIQUE,
	StartDate DATE,
	FinishDate DATE,
	VIN VARCHAR(10) REFERENCES CIS310Vehicle(VIN),
	CustID INT REFERENCES CIS310Customer(CustID),
	CONSTRAINT RepairID_PK PRIMARY KEY(RepairID),
	CONSTRAINT VIN_FK1 FOREIGN KEY (VIN) REFERENCES CIS310Vehicle(VIN),
	CONSTRAINT CustID_FK2 FOREIGN KEY (CustID) REFERENCES CIS310Customer (CustID)
);